### ISSUE TITLE
Handling Unusual Podcasts File Names

### ISSUE THREAD

**Issue by jasttw** [dreamflasher/backup-podcasts#3]
Hello!

I have spent some time experimenting and wanted to see how can it be possible to handle naming for some cases.

1- Podcasts with the same name:

I made a quick search for podcasts with the title "Football Talk".  There were at least 12 podcasts with the same name. I have tried to backup two of them and they both were save in the same folder of  "Football Talk". Maybe an option to append another detail of the podcast such as creator to the folder name can help reduce the possiblity of this happening.

2- Backing up unsual podcast episode titles:

I have found a podcast that has all episodes with the same name (a date). Now I understand that backup podcasts skips the next episodes if they have the same title. It seems not to consider the pubDate before determining a duplicate file. In the case of this podcast the pubDate is different but the titles are the same. I would suggest including the pubDate in the criteria and, as I have seen in podcast addict, include the hours,minutes,seconds of the pubDate to further reduce the possiblity of falsely assuming duplicates.

`<outline text="Sadness" type="rss" xmlUrl="https://anchor.fm/s/456d05c/podcast/rss" htmlUrl="https://podcasters.spotify.com/pod/show/summer-victoria" imageUrl="https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded/627983/627983-1527038366094-e8f7ee4093c11.jpg" />`

3- Hypothitocally, how are the the downloaded file names stored if the title was unusual and exceed the maximum character length limit for the file or the the whole path? I haven't come across something like this before but it's possible if the chosen destination has a long path. Will it throw an error for that specific episode(s) and resume with the rest or just stop? Maybe we can test this with with a custom xml pointing to link with a very long name.

Thanks

**Comment by jasttw** [comment]
Alright so I found the answer to the third part. It gives `([Errno 36] File name too long:`


Maybe an option to only store it with only the date and time can be helpful. The name can be found in the meta.

I think it should just skip the problematic file and just continue with the rest with a kind of summary in the end to show how many completed and how many failed.

Link to podcast:
`<outline text="the memory palace" title="the memory palace" type="rss" htmlUrl="http://feeds.thememorypalace.us/thememorypalace" xmlUrl="http://feeds.thememorypalace.us/thememorypalace" />`

**Comment by dreamflasher** [comment]
Hey there! Sorry for my late response, Github decided to not send me notifications about your issue.

1) One would either need to include the URL (because that's the only unique property of a podcast) in the foldername, or do a mapping URL → name in an additional file, which is something I'd need for this issue anyways: https://github.com/dreamflasher/backup-podcasts/issues/4 

2) Solution would be to include the full pubdate is included in the filename, currently the pubdate is included without minutes and seconds. Does your podcast publish more than once a day?

3) Too long file names are shortened, can you open a new issue if you have an example where it doesn't work? (you reported 3 issues in one, making it difficult to handle one at a time)

**Comment by dreamflasher** [comment]
@jasttw I just pushed https://github.com/dreamflasher/backup-podcasts/commit/c2da1519204870a81d9a0e89f63080e7ec8c6432 – which handles the mapping from url to foldername. This solves your issue (1). 

If (2) and (3) are still an issue, please open seperate issues answering my questions. Thanks!
